# Generated by Django 5.0.6 on 2024-05-22 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Comment text')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
            },
        ),
        migrations.CreateModel(
            name='DiseaseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Disease category title')),
                ('description', models.TextField(blank=True, verbose_name='Disease category description')),
            ],
            options={
                'verbose_name': 'Disease category',
                'verbose_name_plural': 'Disease categories',
            },
        ),
        migrations.CreateModel(
            name='DiseasePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Title')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated date')),
            ],
            options={
                'verbose_name': 'Disease post',
                'verbose_name_plural': 'Disease posts',
            },
        ),
        migrations.CreateModel(
            name='DiseasePostAttachments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.FileField(upload_to='uploads/post_attachments/', verbose_name='Attachment')),
            ],
            options={
                'verbose_name': 'Disease post',
                'verbose_name_plural': 'Disease posts',
            },
        ),
    ]
